//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class DescribeParameters_ResponseMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/DescribeParameters_Response";
        public override string RosMessageName => k_RosMessageName;

        //  A list of the descriptors of all parameters requested in the same order
        //  as they were requested. This list has the same length as the list of
        //  parameters requested.
        public ParameterDescriptorMsg[] descriptors;

        public DescribeParameters_ResponseMsg()
        {
            this.descriptors = new ParameterDescriptorMsg[0];
        }

        public DescribeParameters_ResponseMsg(ParameterDescriptorMsg[] descriptors)
        {
            this.descriptors = descriptors;
        }

        public static DescribeParameters_ResponseMsg Deserialize(MessageDeserializer deserializer) => new DescribeParameters_ResponseMsg(deserializer);

        private DescribeParameters_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.descriptors, ParameterDescriptorMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.descriptors);
            serializer.Write(this.descriptors);
        }

        public override string ToString()
        {
            return "DescribeParameters_ResponseMsg: " +
            "\ndescriptors: " + System.String.Join(", ", descriptors.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
