//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class GetParameterTypes_ResponseMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/GetParameterTypes_Response";
        public override string RosMessageName => k_RosMessageName;

        //  List of types which is the same length and order as the provided names.
        // 
        //  The type enum is defined in ParameterType.msg. ParameterType.PARAMETER_NOT_SET
        //  indicates that the parameter is not currently set.
        public byte[] types;

        public GetParameterTypes_ResponseMsg()
        {
            this.types = new byte[0];
        }

        public GetParameterTypes_ResponseMsg(byte[] types)
        {
            this.types = types;
        }

        public static GetParameterTypes_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GetParameterTypes_ResponseMsg(deserializer);

        private GetParameterTypes_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.types, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.types);
            serializer.Write(this.types);
        }

        public override string ToString()
        {
            return "GetParameterTypes_ResponseMsg: " +
            "\ntypes: " + System.String.Join(", ", types.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
