//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class GetParameters_ResponseMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/GetParameters_Response";
        public override string RosMessageName => k_RosMessageName;

        //  List of values which is the same length and order as the provided names. If a
        //  parameter was not yet set, the value will have PARAMETER_NOT_SET as the
        //  type.
        public ParameterValueMsg[] values;

        public GetParameters_ResponseMsg()
        {
            this.values = new ParameterValueMsg[0];
        }

        public GetParameters_ResponseMsg(ParameterValueMsg[] values)
        {
            this.values = values;
        }

        public static GetParameters_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GetParameters_ResponseMsg(deserializer);

        private GetParameters_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.values, ParameterValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
        }

        public override string ToString()
        {
            return "GetParameters_ResponseMsg: " +
            "\nvalues: " + System.String.Join(", ", values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
