//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class ListParametersResultMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/ListParametersResult";
        public override string RosMessageName => k_RosMessageName;

        //  The resulting parameters under the given prefixes.
        public string[] names;
        //  The resulting prefixes under the given prefixes.
        //  TODO(wjwwood): link to prefix definition and rules.
        public string[] prefixes;

        public ListParametersResultMsg()
        {
            this.names = new string[0];
            this.prefixes = new string[0];
        }

        public ListParametersResultMsg(string[] names, string[] prefixes)
        {
            this.names = names;
            this.prefixes = prefixes;
        }

        public static ListParametersResultMsg Deserialize(MessageDeserializer deserializer) => new ListParametersResultMsg(deserializer);

        private ListParametersResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.prefixes, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.prefixes);
            serializer.Write(this.prefixes);
        }

        public override string ToString()
        {
            return "ListParametersResultMsg: " +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nprefixes: " + System.String.Join(", ", prefixes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
