//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class ParameterEventMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/ParameterEvent";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains a parameter event.
        //  Because the parameter event was an atomic update, a specific parameter name
        //  can only be in one of the three sets.
        //  The time stamp when this parameter event occurred.
        public BuiltinInterfaces.TimeMsg stamp;
        //  Fully qualified ROS path to node.
        public string node;
        //  New parameters that have been set for this node.
        public ParameterMsg[] new_parameters;
        //  Parameters that have been changed during this event.
        public ParameterMsg[] changed_parameters;
        //  Parameters that have been deleted during this event.
        public ParameterMsg[] deleted_parameters;

        public ParameterEventMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.node = "";
            this.new_parameters = new ParameterMsg[0];
            this.changed_parameters = new ParameterMsg[0];
            this.deleted_parameters = new ParameterMsg[0];
        }

        public ParameterEventMsg(BuiltinInterfaces.TimeMsg stamp, string node, ParameterMsg[] new_parameters, ParameterMsg[] changed_parameters, ParameterMsg[] deleted_parameters)
        {
            this.stamp = stamp;
            this.node = node;
            this.new_parameters = new_parameters;
            this.changed_parameters = changed_parameters;
            this.deleted_parameters = deleted_parameters;
        }

        public static ParameterEventMsg Deserialize(MessageDeserializer deserializer) => new ParameterEventMsg(deserializer);

        private ParameterEventMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.node);
            deserializer.Read(out this.new_parameters, ParameterMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.changed_parameters, ParameterMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.deleted_parameters, ParameterMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.node);
            serializer.WriteLength(this.new_parameters);
            serializer.Write(this.new_parameters);
            serializer.WriteLength(this.changed_parameters);
            serializer.Write(this.changed_parameters);
            serializer.WriteLength(this.deleted_parameters);
            serializer.Write(this.deleted_parameters);
        }

        public override string ToString()
        {
            return "ParameterEventMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nnode: " + node.ToString() +
            "\nnew_parameters: " + System.String.Join(", ", new_parameters.ToList()) +
            "\nchanged_parameters: " + System.String.Join(", ", changed_parameters.ToList()) +
            "\ndeleted_parameters: " + System.String.Join(", ", deleted_parameters.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
