//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class ParameterEventDescriptorsMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/ParameterEventDescriptors";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains descriptors of a parameter event.
        //  It was an atomic update.
        //  A specific parameter name can only be in one of the three sets.
        public ParameterDescriptorMsg[] new_parameters;
        public ParameterDescriptorMsg[] changed_parameters;
        public ParameterDescriptorMsg[] deleted_parameters;

        public ParameterEventDescriptorsMsg()
        {
            this.new_parameters = new ParameterDescriptorMsg[0];
            this.changed_parameters = new ParameterDescriptorMsg[0];
            this.deleted_parameters = new ParameterDescriptorMsg[0];
        }

        public ParameterEventDescriptorsMsg(ParameterDescriptorMsg[] new_parameters, ParameterDescriptorMsg[] changed_parameters, ParameterDescriptorMsg[] deleted_parameters)
        {
            this.new_parameters = new_parameters;
            this.changed_parameters = changed_parameters;
            this.deleted_parameters = deleted_parameters;
        }

        public static ParameterEventDescriptorsMsg Deserialize(MessageDeserializer deserializer) => new ParameterEventDescriptorsMsg(deserializer);

        private ParameterEventDescriptorsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.new_parameters, ParameterDescriptorMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.changed_parameters, ParameterDescriptorMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.deleted_parameters, ParameterDescriptorMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.new_parameters);
            serializer.Write(this.new_parameters);
            serializer.WriteLength(this.changed_parameters);
            serializer.Write(this.changed_parameters);
            serializer.WriteLength(this.deleted_parameters);
            serializer.Write(this.deleted_parameters);
        }

        public override string ToString()
        {
            return "ParameterEventDescriptorsMsg: " +
            "\nnew_parameters: " + System.String.Join(", ", new_parameters.ToList()) +
            "\nchanged_parameters: " + System.String.Join(", ", changed_parameters.ToList()) +
            "\ndeleted_parameters: " + System.String.Join(", ", deleted_parameters.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
