//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class SetParametersResultMsg : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/SetParametersResult";
        public override string RosMessageName => k_RosMessageName;

        //  A true value of the same index indicates that the parameter was set
        //  successfully. A false value indicates the change was rejected.
        public bool successful;
        //  Reason why the setting was either successful or a failure. This should only be
        //  used for logging and user interfaces.
        public string reason;

        public SetParametersResultMsg()
        {
            this.successful = false;
            this.reason = "";
        }

        public SetParametersResultMsg(bool successful, string reason)
        {
            this.successful = successful;
            this.reason = reason;
        }

        public static SetParametersResultMsg Deserialize(MessageDeserializer deserializer) => new SetParametersResultMsg(deserializer);

        private SetParametersResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.successful);
            deserializer.Read(out this.reason);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.successful);
            serializer.Write(this.reason);
        }

        public override string ToString()
        {
            return "SetParametersResultMsg: " +
            "\nsuccessful: " + successful.ToString() +
            "\nreason: " + reason.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
