//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlesim
{
    [Serializable]
    public class SetPenRequest : Message
    {
        public const string k_RosMessageName = "turtlesim/SetPen";
        public override string RosMessageName => k_RosMessageName;

        public byte r;
        public byte g;
        public byte b;
        public byte width;
        public byte off;

        public SetPenRequest()
        {
            this.r = 0;
            this.g = 0;
            this.b = 0;
            this.width = 0;
            this.off = 0;
        }

        public SetPenRequest(byte r, byte g, byte b, byte width, byte off)
        {
            this.r = r;
            this.g = g;
            this.b = b;
            this.width = width;
            this.off = off;
        }

        public static SetPenRequest Deserialize(MessageDeserializer deserializer) => new SetPenRequest(deserializer);

        private SetPenRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.r);
            deserializer.Read(out this.g);
            deserializer.Read(out this.b);
            deserializer.Read(out this.width);
            deserializer.Read(out this.off);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.r);
            serializer.Write(this.g);
            serializer.Write(this.b);
            serializer.Write(this.width);
            serializer.Write(this.off);
        }

        public override string ToString()
        {
            return "SetPenRequest: " +
            "\nr: " + r.ToString() +
            "\ng: " + g.ToString() +
            "\nb: " + b.ToString() +
            "\nwidth: " + width.ToString() +
            "\noff: " + off.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
