//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlesim
{
    [Serializable]
    public class SetPenResponse : Message
    {
        public const string k_RosMessageName = "turtlesim/SetPen";
        public override string RosMessageName => k_RosMessageName;


        public SetPenResponse()
        {
        }
        public static SetPenResponse Deserialize(MessageDeserializer deserializer) => new SetPenResponse(deserializer);

        private SetPenResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SetPenResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
