//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlesim
{
    [Serializable]
    public class SpawnResponse : Message
    {
        public const string k_RosMessageName = "turtlesim/Spawn";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public SpawnResponse()
        {
            this.name = "";
        }

        public SpawnResponse(string name)
        {
            this.name = name;
        }

        public static SpawnResponse Deserialize(MessageDeserializer deserializer) => new SpawnResponse(deserializer);

        private SpawnResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "SpawnResponse: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
