//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlesim
{
    [Serializable]
    public class TeleportAbsoluteResponse : Message
    {
        public const string k_RosMessageName = "turtlesim/TeleportAbsolute";
        public override string RosMessageName => k_RosMessageName;


        public TeleportAbsoluteResponse()
        {
        }
        public static TeleportAbsoluteResponse Deserialize(MessageDeserializer deserializer) => new TeleportAbsoluteResponse(deserializer);

        private TeleportAbsoluteResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "TeleportAbsoluteResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
