//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlesim
{
    [Serializable]
    public class TeleportRelativeRequest : Message
    {
        public const string k_RosMessageName = "turtlesim/TeleportRelative";
        public override string RosMessageName => k_RosMessageName;

        public float linear;
        public float angular;

        public TeleportRelativeRequest()
        {
            this.linear = 0.0f;
            this.angular = 0.0f;
        }

        public TeleportRelativeRequest(float linear, float angular)
        {
            this.linear = linear;
            this.angular = angular;
        }

        public static TeleportRelativeRequest Deserialize(MessageDeserializer deserializer) => new TeleportRelativeRequest(deserializer);

        private TeleportRelativeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.linear);
            deserializer.Read(out this.angular);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear);
            serializer.Write(this.angular);
        }

        public override string ToString()
        {
            return "TeleportRelativeRequest: " +
            "\nlinear: " + linear.ToString() +
            "\nangular: " + angular.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
