//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlesim
{
    [Serializable]
    public class PoseMsg : Message
    {
        public const string k_RosMessageName = "turtlesim/Pose";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float theta;
        public float linear_velocity;
        public float angular_velocity;

        public PoseMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.theta = 0.0f;
            this.linear_velocity = 0.0f;
            this.angular_velocity = 0.0f;
        }

        public PoseMsg(float x, float y, float theta, float linear_velocity, float angular_velocity)
        {
            this.x = x;
            this.y = y;
            this.theta = theta;
            this.linear_velocity = linear_velocity;
            this.angular_velocity = angular_velocity;
        }

        public static PoseMsg Deserialize(MessageDeserializer deserializer) => new PoseMsg(deserializer);

        private PoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.theta);
            deserializer.Read(out this.linear_velocity);
            deserializer.Read(out this.angular_velocity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.theta);
            serializer.Write(this.linear_velocity);
            serializer.Write(this.angular_velocity);
        }

        public override string ToString()
        {
            return "PoseMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\ntheta: " + theta.ToString() +
            "\nlinear_velocity: " + linear_velocity.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
