//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class DescribeParametersResponse : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/DescribeParameters";
        public override string RosMessageName => k_RosMessageName;

        //  A list of the descriptors of all parameters requested in the same order
        //  as they were requested. This list has the same length as the list of
        //  parameters requested.
        public ParameterDescriptorMsg[] descriptors;

        public DescribeParametersResponse()
        {
            this.descriptors = new ParameterDescriptorMsg[0];
        }

        public DescribeParametersResponse(ParameterDescriptorMsg[] descriptors)
        {
            this.descriptors = descriptors;
        }

        public static DescribeParametersResponse Deserialize(MessageDeserializer deserializer) => new DescribeParametersResponse(deserializer);

        private DescribeParametersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.descriptors, ParameterDescriptorMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.descriptors);
            serializer.Write(this.descriptors);
        }

        public override string ToString()
        {
            return "DescribeParametersResponse: " +
            "\ndescriptors: " + System.String.Join(", ", descriptors.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
