//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class GetParametersResponse : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/GetParameters";
        public override string RosMessageName => k_RosMessageName;

        //  List of values which is the same length and order as the provided names. If a
        //  parameter was not yet set, the value will have PARAMETER_NOT_SET as the
        //  type.
        public ParameterValueMsg[] values;

        public GetParametersResponse()
        {
            this.values = new ParameterValueMsg[0];
        }

        public GetParametersResponse(ParameterValueMsg[] values)
        {
            this.values = values;
        }

        public static GetParametersResponse Deserialize(MessageDeserializer deserializer) => new GetParametersResponse(deserializer);

        private GetParametersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.values, ParameterValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
        }

        public override string ToString()
        {
            return "GetParametersResponse: " +
            "\nvalues: " + System.String.Join(", ", values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
