//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class GetParametersRequest : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/GetParameters";
        public override string RosMessageName => k_RosMessageName;

        //  TODO(wjwwood): Decide on the rules for grouping, nodes, and parameter "names"
        //  in general, then link to that.
        // 
        //  For more information about parameters and naming rules, see:
        //  https://design.ros2.org/articles/ros_parameters.html
        //  https://github.com/ros2/design/pull/241
        //  A list of parameter names to get.
        public string[] names;

        public GetParametersRequest()
        {
            this.names = new string[0];
        }

        public GetParametersRequest(string[] names)
        {
            this.names = names;
        }

        public static GetParametersRequest Deserialize(MessageDeserializer deserializer) => new GetParametersRequest(deserializer);

        private GetParametersRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
        }

        public override string ToString()
        {
            return "GetParametersRequest: " +
            "\nnames: " + System.String.Join(", ", names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
