//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class ListParametersRequest : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/ListParameters";
        public override string RosMessageName => k_RosMessageName;

        //  Recursively get parameters with unlimited depth.
        public const ulong DEPTH_RECURSIVE = 0;
        //  The list of parameter prefixes to query.
        public string[] prefixes;
        //  Relative depth from given prefixes to return.
        // 
        //  Use DEPTH_RECURSIVE to get the recursive parameters and prefixes for each prefix.
        public ulong depth;

        public ListParametersRequest()
        {
            this.prefixes = new string[0];
            this.depth = 0;
        }

        public ListParametersRequest(string[] prefixes, ulong depth)
        {
            this.prefixes = prefixes;
            this.depth = depth;
        }

        public static ListParametersRequest Deserialize(MessageDeserializer deserializer) => new ListParametersRequest(deserializer);

        private ListParametersRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.prefixes, deserializer.ReadLength());
            deserializer.Read(out this.depth);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.prefixes);
            serializer.Write(this.prefixes);
            serializer.Write(this.depth);
        }

        public override string ToString()
        {
            return "ListParametersRequest: " +
            "\nprefixes: " + System.String.Join(", ", prefixes.ToList()) +
            "\ndepth: " + depth.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
