//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class ListParametersResponse : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/ListParameters";
        public override string RosMessageName => k_RosMessageName;

        //  The list of parameter names and their prefixes.
        public ListParametersResultMsg result;

        public ListParametersResponse()
        {
            this.result = new ListParametersResultMsg();
        }

        public ListParametersResponse(ListParametersResultMsg result)
        {
            this.result = result;
        }

        public static ListParametersResponse Deserialize(MessageDeserializer deserializer) => new ListParametersResponse(deserializer);

        private ListParametersResponse(MessageDeserializer deserializer)
        {
            this.result = ListParametersResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "ListParametersResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
