//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RclInterfaces
{
    [Serializable]
    public class SetParametersAtomicallyResponse : Message
    {
        public const string k_RosMessageName = "rcl_interfaces/SetParametersAtomically";
        public override string RosMessageName => k_RosMessageName;

        //  Indicates whether setting all of the parameters succeeded or not and why.
        public SetParametersResultMsg result;

        public SetParametersAtomicallyResponse()
        {
            this.result = new SetParametersResultMsg();
        }

        public SetParametersAtomicallyResponse(SetParametersResultMsg result)
        {
            this.result = result;
        }

        public static SetParametersAtomicallyResponse Deserialize(MessageDeserializer deserializer) => new SetParametersAtomicallyResponse(deserializer);

        private SetParametersAtomicallyResponse(MessageDeserializer deserializer)
        {
            this.result = SetParametersResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "SetParametersAtomicallyResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
